#!/usr/bin/env python3
"""Regenerate the landing page's seed catalogue from catalog.tsv.

The page resolves newly released milestones itself at runtime, so this is not what
keeps the shelf current - it keeps the *first paint* current, before any fetch has
come back. Nothing else in the page needs syncing: no prose, title, meta or JSON-LD
names a count or a version range, precisely so that none of it can go stale.

    python3 tools/sync-landing.py            # rewrite docs/index.html
    python3 tools/sync-landing.py --check    # report drift, do not write
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "catalog.tsv")
PAGE = os.path.join(ROOT, "docs", "index.html")

SEED_BEGIN = "  /* seed:begin - regenerated by tools/sync-landing.py from catalog.tsv */\n"
SEED_END = "  /* seed:end */"

# The shelf describes one host - an Apple Silicon Mac - because that is what the
# screenshot above it shows. Everything else on the page is platform-neutral.
NATIVE, ROSETTA = "native arm64", "x86_64 · Rosetta"


def read_catalog():
    rows = []
    builds = {}
    with open(CATALOG) as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if parts[0] == "V":
                rows.append({
                    "milestone": int(parts[1]),
                    "version": parts[2],
                    "note": parts[3] if len(parts) > 3 else "",
                })
            elif parts[0] == "B":
                builds.setdefault(int(parts[1]), {})[parts[2]] = parts[3]
    return rows, builds


def seed_entries(rows, builds):
    """One line per milestone, in the shape the page's SEED array expects."""
    entries = []
    for row in rows:
        available = builds.get(row["milestone"], {})
        revision = available.get("Mac_Arm") or available.get("Mac")
        if not revision:
            continue
        year, _, note = row["note"].partition(". ")
        if not re.fullmatch(r"\d{4}", year):
            year, note = "", row["note"]
        entries.append({
            "v": str(row["milestone"]),
            "full": row["version"],
            "rev": revision,
            "plat": NATIVE if "Mac_Arm" in available else ROSETTA,
            "year": year,
            # The catalog is plain ASCII so it stays diffable; the page is prose.
            "note": note.replace(" - ", " — ").replace("'", "\\'"),
        })
    return entries


def seed_block(entries):
    lines = [SEED_BEGIN, "  const SEED = [\n"]
    for i, e in enumerate(entries):
        comma = "" if i == len(entries) - 1 else ","
        lines.append(
            "    {{v:'{v}', full:'{full}', rev:'{rev}', plat:'{plat}', "
            "year:'{year}', note:'{note}'}}{comma}\n".format(comma=comma, **e)
        )
    lines.append("  ];\n")
    lines.append(SEED_END)
    return "".join(lines)


def rewrite(text, entries):
    start = text.index(SEED_BEGIN)
    end = text.index(SEED_END) + len(SEED_END)
    text = text[:start] + seed_block(entries) + text[end:]
    # Not prose, and not claims: two values the page recomputes from live data on
    # load. They only have to be right for the moment before the script runs - and
    # for whoever is reading with JavaScript off.
    text = re.sub(r'aria-valuemax="\d+"', 'aria-valuemax="{}"'.format(len(entries) - 1), text)
    return re.sub(r'(id="mockVer"[^>]*>)Chromium \d+',
                  r'\g<1>Chromium {}'.format(entries[-1]["v"]), text)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report drift, do not write")
    args = parser.parse_args()

    rows, builds = read_catalog()
    entries = seed_entries(rows, builds)
    if not entries:
        print("catalog.tsv has no usable rows", file=sys.stderr)
        return 1

    current = open(PAGE, encoding="utf-8").read()
    updated = rewrite(current, entries)

    if args.check:
        if current == updated:
            print("docs/index.html is up to date")
            return 0
        print("docs/index.html is behind catalog.tsv", file=sys.stderr)
        return 1
    if current == updated:
        print("docs/index.html already matches catalog.tsv")
        return 0
    with open(PAGE, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print(f"wrote {PAGE}: {len(entries)} milestones, {entries[0]['v']} to {entries[-1]['v']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
