#!/usr/bin/env python3
"""Regenerate the landing page's seed catalogue from catalog.tsv.

Two blocks, because the page needs two different things.

SEED is Chromium: milestone, full version, snapshot revision and the editorial
note that goes with it. The page resolves newly released milestones itself at
runtime, so this is not what keeps that shelf current - it keeps the *first
paint* current, before any fetch has come back.

SHELF is the other three engines, off the S rows tools/discover.py writes. There
is no runtime top-up for those: Mozilla's index, Microsoft's enterprise feed and
Playwright's release list are all fetched server-side by discover.py and none of
them answer a browser (no CORS). So the shelf a visitor sees for Firefox, Edge
and WebKit is exactly what was catalogued the last time discover.py ran - which
is why this runs after it, not instead of it.

Nothing else in the page needs syncing: no prose, title, meta or JSON-LD names a
count or a version range, precisely so that none of it can go stale.

    python3 tools/sync-landing.py            # rewrite docs/index.html
    python3 tools/sync-landing.py --check    # report drift, do not write
"""
import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "catalog.tsv")
PAGE = os.path.join(ROOT, "docs", "index.html")

SEED_BEGIN = "  /* seed:begin - regenerated by tools/sync-landing.py from catalog.tsv */\n"
SEED_END = "  /* seed:end */"
SHELF_BEGIN = "  /* shelf:begin - regenerated by tools/sync-landing.py from catalog.tsv */\n"
SHELF_END = "  /* shelf:end */"

# Chromium is not in here: it has SEED, which carries a revision and a note that
# no S row has. These three are the ones the scrubber has nothing else to go on.
SHELF_ENGINES = ("firefox", "edge", "webkit")

# The shelf describes one host - an Apple Silicon Mac - because that is what the
# screenshot above it shows. Everything else on the page is platform-neutral.
NATIVE, ROSETTA = "native arm64", "x86_64 · Rosetta"


def read_catalog():
    rows = []
    builds = {}
    shelf = {engine: [] for engine in SHELF_ENGINES}
    seen = set()
    with open(CATALOG) as handle:
        for line in handle:
            if line.startswith("#") or not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if parts[0] == "V":
                rows.append({
                    "milestone": int(parts[1]),
                    "version": parts[2],
                    "note": parts[3] if len(parts) > 3 else "",
                })
            elif parts[0] == "B":
                builds.setdefault(int(parts[1]), {})[parts[2]] = parts[3]
            elif parts[0] == "S" and len(parts) >= 6 and parts[1] in shelf:
                # Two WebKit builds can carry the same published name, so the id
                # is the identity - and the same id twice is a stale row the
                # rewrite left behind, not a second release.
                key = (parts[1], parts[3])
                if key in seen:
                    continue
                seen.add(key)
                shelf[parts[1]].append((parts[3], parts[4], parts[5]))
    for releases in shelf.values():
        releases.sort(key=lambda r: r[2])
    return rows, builds, shelf


def seed_entries(rows, builds):
    """One line per milestone, in the shape the page's SEED array expects."""
    entries = []
    for row in rows:
        available = builds.get(row["milestone"], {})
        revision = available.get("Mac_Arm") or available.get("Mac")
        if not revision:
            continue
        year, _, note = row["note"].partition(". ")
        if not re.fullmatch(r"\d{4}", year):
            year, note = "", row["note"]
        entries.append({
            "v": str(row["milestone"]),
            "full": row["version"],
            "rev": revision,
            "plat": NATIVE if "Mac_Arm" in available else ROSETTA,
            "year": year,
            # The catalog is plain ASCII so it stays diffable; the page is prose.
            "note": note.replace(" - ", " — ").replace("'", "\\'"),
        })
    return entries


def shelf_block(shelf):
    """One line per release, packed: 'id|label|date'.

    The page splits it back apart. A row is three short strings and there are a
    couple of hundred of them; spelt out as objects, one field per line the way
    SEED is, they would add a thousand lines to a file a browser has to parse
    before it can paint anything.
    """
    lines = [SHELF_BEGIN, "  const SHELF = {\n"]
    for engine in SHELF_ENGINES:
        releases = shelf.get(engine) or []
        lines.append("    %s: [\n" % engine)
        for release in releases:
            lines.append("      '%s|%s|%s',\n" % release)
        lines.append("    ],\n")
    lines.append("  };\n")
    lines.append(SHELF_END)
    return "".join(lines)


def seed_block(entries):
    lines = [SEED_BEGIN, "  const SEED = [\n"]
    for i, e in enumerate(entries):
        comma = "" if i == len(entries) - 1 else ","
        lines.append(
            "    {{v:'{v}', full:'{full}', rev:'{rev}', plat:'{plat}', "
            "year:'{year}', note:'{note}'}}{comma}\n".format(comma=comma, **e)
        )
    lines.append("  ];\n")
    lines.append(SEED_END)
    return "".join(lines)


def replace_block(text, begin, end, body):
    start = text.index(begin)
    stop = text.index(end) + len(end)
    return text[:start] + body + text[stop:]


def rewrite(text, entries, shelf):
    text = replace_block(text, SEED_BEGIN, SEED_END, seed_block(entries))
    text = replace_block(text, SHELF_BEGIN, SHELF_END, shelf_block(shelf))
    # Not prose, and not claims: two values the page recomputes from live data on
    # load. They only have to be right for the moment before the script runs - and
    # for whoever is reading with JavaScript off.
    text = re.sub(r'aria-valuemax="\d+"', 'aria-valuemax="{}"'.format(len(entries) - 1), text)
    return re.sub(r'(id="mockVer"[^>]*>)Chromium \d+',
                  r'\g<1>Chromium {}'.format(entries[-1]["v"]), text)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="report drift, do not write")
    args = parser.parse_args()

    rows, builds, shelf = read_catalog()
    entries = seed_entries(rows, builds)
    if not entries:
        print("catalog.tsv has no usable rows", file=sys.stderr)
        return 1
    # An engine with no rows at all means discover.py has never run for it, or
    # ran and could not reach the vendor. Emptying its tab on the page would
    # read as "this engine is gone" rather than "nobody asked recently".
    empty = [e for e in SHELF_ENGINES if not shelf.get(e)]
    if empty:
        print("no shelf rows for %s - run tools/discover.py --write"
              % ", ".join(empty), file=sys.stderr)

    current = open(PAGE, encoding="utf-8").read()
    updated = rewrite(current, entries, shelf)

    if args.check:
        if current == updated:
            print("docs/index.html is up to date")
            return 0
        print("docs/index.html is behind catalog.tsv", file=sys.stderr)
        return 1
    if current == updated:
        print("docs/index.html already matches catalog.tsv")
        return 0
    with open(PAGE, "w", encoding="utf-8") as handle:
        handle.write(updated)
    print(f"wrote {PAGE}: {len(entries)} milestones, {entries[0]['v']} to {entries[-1]['v']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
